name: pull-docs-from-main

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 4 * * 5' # 4:40am on Fridays
  workflow_dispatch:
    inputs:
      notes:
        description: 'Anything you want to say'
        default: 'anything at all'
        required: false

jobs:
  update-docs-in-data:
    runs-on: ubuntu-latest
    steps:
      - name: Log the notes
        run: echo ${{ github.event.inputs.notes }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: data
      - name: Merge from main
        run: |
          git config user.name intoverflow
          git config user.email intoverflow@users.noreply.github.com
          git fetch origin main
          git merge -s recursive -X theirs --allow-unrelated-histories origin/main
      - name: Delete and restore the docs
        run: |
          git rm -r docs || true
          git checkout origin/main -- docs
      - name: Push
        run: |
          git config user.name intoverflow
          git config user.email intoverflow@users.noreply.github.com
          git add docs
          git commit -m "pull-docs-from-main" || true
          git push
  update-docs-in-docs:
    needs: update-docs-in-data
    runs-on: ubuntu-latest
    steps:
      - name: Log the notes
        run: echo ${{ github.event.inputs.notes }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: docs
      - name: Rebase on data
        run: |
          git config user.name intoverflow
          git config user.email intoverflow@users.noreply.github.com
          git pull --rebase -s recursive -X theirs origin data
      - name: Install the dependencies
        run: pip install -r requirements.txt
      - name: Render the plots
        run: python3 src/plot.py
      - name: Commit and push
        run: |
          git config user.name intoverflow
          git config user.email intoverflow@users.noreply.github.com
          git add .
          git add --force docs/source/_static/plots
          git commit -m "pull-docs-from-main" || true
          git push
