name: pull-docs-from-main

on:
  workflow_dispatch:
    inputs:
      notes:
        description: 'Anything you want to say'
        default: 'anything at all'
        required: false

jobs:
  do-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Log the notes
        run: echo ${{ github.event.inputs.notes }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: data
      - name: Delete the docs
        run: |
          git rm -r docs || true
      - name: Merge from main
        run: |
          git config user.name intoverflow
          git config user.email intoverflow@users.noreply.github.com
          git fetch origin main
          git checkout origin/main -- docs
      - name: Push
        run: |
          git config user.name intoverflow
          git config user.email intoverflow@users.noreply.github.com
          git add docs
          git commit -m "refresh docs" || true
          git push
